"""add_optimization_models

Revision ID: 21b4bcbe7ba0
Revises: ffb5ec45e5ac
Create Date: 2026-01-13 20:16:22.204085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b4bcbe7ba0'
down_revision: Union[str, None] = 'ffb5ec45e5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llms_txt_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.JSON(), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llms_txt_results', schema=None) as batch_op:
        batch_op.create_index('ix_llms_txt_domain_created', ['domain', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llms_txt_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llms_txt_results_domain'), ['domain'], unique=False)

    op.create_table('optimization_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('recommendations_generated', sa.Integer(), nullable=False),
    sa.Column('recommendations_completed', sa.Integer(), nullable=False),
    sa.Column('recommendations_dismissed', sa.Integer(), nullable=False),
    sa.Column('llms_txt_generated', sa.Integer(), nullable=False),
    sa.Column('avg_impact_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_stats_date'), ['date'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('brand_normalized', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_steps_json', sa.JSON(), nullable=True),
    sa.Column('expected_impact', sa.String(length=255), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source_json', sa.JSON(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False, comment='0-100 impact score'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_brand_normalized'), ['brand_normalized'], unique=False)
        batch_op.create_index('ix_recommendations_brand_status', ['brand_normalized', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_priority'), ['priority'], unique=False)
        batch_op.create_index('ix_recommendations_priority_status', ['priority', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index('ix_recommendations_priority_status')
        batch_op.drop_index(batch_op.f('ix_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.drop_index(batch_op.f('ix_recommendations_category'))
        batch_op.drop_index('ix_recommendations_brand_status')
        batch_op.drop_index(batch_op.f('ix_recommendations_brand_normalized'))
        batch_op.drop_index(batch_op.f('ix_recommendations_brand'))

    op.drop_table('recommendations')
    with op.batch_alter_table('optimization_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_stats_date'))

    op.drop_table('optimization_stats')
    with op.batch_alter_table('llms_txt_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llms_txt_results_domain'))
        batch_op.drop_index(batch_op.f('ix_llms_txt_results_created_at'))
        batch_op.drop_index('ix_llms_txt_domain_created')

    op.drop_table('llms_txt_results')
    # ### end Alembic commands ###
