"""add_analysis_models

Revision ID: 2453460ad919
Revises: 68f9c8439dc1
Create Date: 2026-01-13 18:49:16.794682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2453460ad919'
down_revision: Union[str, None] = '68f9c8439dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('normalized_word', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('related_topics', sa.JSON(), nullable=True),
    sa.Column('related_brands', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index('ix_keywords_count', ['count'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_normalized_word'), ['normalized_word'], unique=True)
        batch_op.create_index(batch_op.f('ix_keywords_word'), ['word'], unique=True)

    op.create_table('sentiment_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_normalized', sa.String(length=255), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('overall_sentiment', sa.Float(), nullable=False, comment='-1.0 to 1.0'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('positive_pct', sa.Float(), nullable=False),
    sa.Column('neutral_pct', sa.Float(), nullable=False),
    sa.Column('negative_pct', sa.Float(), nullable=False),
    sa.Column('positive_samples', sa.JSON(), nullable=True),
    sa.Column('negative_samples', sa.JSON(), nullable=True),
    sa.Column('mentions_analyzed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_analyses_analysis_date'), ['analysis_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_analyses_brand_normalized'), ['brand_normalized'], unique=False)
        batch_op.create_index('ix_sentiment_brand_date', ['brand_normalized', 'analysis_date'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False, comment='% change'),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('related_brands', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_topics_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('competitor_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('owner_brand_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False, comment='Auto-refresh analysis'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_groups_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_groups_name'), ['name'], unique=False)

    op.create_table('comparison_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_normalized', sa.String(length=255), nullable=False),
    sa.Column('competitor_normalized', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('brand_visibility', sa.Float(), nullable=False),
    sa.Column('competitor_visibility', sa.Float(), nullable=False),
    sa.Column('visibility_diff', sa.Float(), nullable=False, comment='brand - competitor'),
    sa.Column('brand_mentions', sa.Integer(), nullable=False),
    sa.Column('competitor_mentions', sa.Integer(), nullable=False),
    sa.Column('mention_diff', sa.Integer(), nullable=False),
    sa.Column('brand_sentiment', sa.Float(), nullable=False),
    sa.Column('competitor_sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_diff', sa.Float(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=True, comment='Claude analysis insights'),
    sa.Column('comparison_date', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['competitor_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparison_results', schema=None) as batch_op:
        batch_op.create_index('ix_comparison_brands', ['brand_normalized', 'competitor_normalized'], unique=False)
        batch_op.create_index('ix_comparison_date', ['comparison_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_results_brand_normalized'), ['brand_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_results_comparison_date'), ['comparison_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparison_results_competitor_normalized'), ['competitor_normalized'], unique=False)

    op.create_table('competitor_group_brands',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['competitor_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'brand_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitor_group_brands')
    with op.batch_alter_table('comparison_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparison_results_competitor_normalized'))
        batch_op.drop_index(batch_op.f('ix_comparison_results_comparison_date'))
        batch_op.drop_index(batch_op.f('ix_comparison_results_brand_normalized'))
        batch_op.drop_index('ix_comparison_date')
        batch_op.drop_index('ix_comparison_brands')

    op.drop_table('comparison_results')
    with op.batch_alter_table('competitor_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_groups_name'))
        batch_op.drop_index(batch_op.f('ix_competitor_groups_category'))

    op.drop_table('competitor_groups')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_topics_name'))

    op.drop_table('topics')
    with op.batch_alter_table('sentiment_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_sentiment_brand_date')
        batch_op.drop_index(batch_op.f('ix_sentiment_analyses_brand_normalized'))
        batch_op.drop_index(batch_op.f('ix_sentiment_analyses_analysis_date'))

    op.drop_table('sentiment_analyses')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_word'))
        batch_op.drop_index(batch_op.f('ix_keywords_normalized_word'))
        batch_op.drop_index('ix_keywords_count')

    op.drop_table('keywords')
    # ### end Alembic commands ###
