"""init_tracking_models

Revision ID: 68f9c8439dc1
Revises: 
Create Date: 2026-01-13 17:45:35.229479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f9c8439dc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True, comment='JSON array of aliases'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False, comment='Mark as competitor for comparison'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_brands_normalized_name'), ['normalized_name'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='Browser session identifier'),
    sa.Column('platform', sa.Enum('CHATGPT', 'CLAUDE', 'PERPLEXITY', 'GEMINI', 'OTHER', name='platform'), nullable=False),
    sa.Column('initial_query', sa.Text(), nullable=False, comment='First user question'),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False, comment='When conversation was captured'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_conversations_platform_date', ['platform', 'captured_at'], unique=False)
        batch_op.create_index('ix_conversations_session', ['session_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=False)

    op.create_table('visibility_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_normalized', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Date of score'),
    sa.Column('platform', sa.Enum('CHATGPT', 'CLAUDE', 'PERPLEXITY', 'GEMINI', 'OTHER', name='platform'), nullable=True, comment='Platform filter, null = all'),
    sa.Column('score', sa.Float(), nullable=False, comment='Final visibility score 0-100'),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('avg_position', sa.Float(), nullable=False, comment='Avg position in responses'),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('position_score', sa.Float(), nullable=False, comment='Score from position'),
    sa.Column('frequency_score', sa.Float(), nullable=False, comment='Score from frequency'),
    sa.Column('sentiment_score', sa.Float(), nullable=False, comment='Score from sentiment'),
    sa.Column('conversation_count', sa.Integer(), nullable=False, comment='Conversations analyzed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visibility_scores', schema=None) as batch_op:
        batch_op.create_index('ix_visibility_brand_date', ['brand_normalized', 'date'], unique=False)
        batch_op.create_index('ix_visibility_date_score', ['date', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_scores_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_scores_brand_normalized'), ['brand_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_scores_date'), ['date'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Order in conversation (0-indexed)'),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When message was sent/received'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_messages_conversation_seq', ['conversation_id', 'sequence'], unique=False)

    op.create_table('brand_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_normalized', sa.String(length=255), nullable=False, comment='Normalized brand name for matching'),
    sa.Column('mention_type', sa.Enum('DIRECT', 'INDIRECT', 'COMPARISON', 'RECOMMENDATION', 'NEGATIVE', name='mentiontype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Character position in response'),
    sa.Column('context', sa.Text(), nullable=False, comment='Surrounding text (±100 chars)'),
    sa.Column('sentiment', sa.Float(), nullable=False, comment='Sentiment score -1.0 to 1.0'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Detection confidence 0.0 to 1.0'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_mentions', schema=None) as batch_op:
        batch_op.create_index('ix_brand_mentions_brand_date', ['brand_normalized', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_mentions_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_mentions_brand_normalized'), ['brand_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_mentions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_mentions_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_brand_mentions_type', ['mention_type', 'brand_normalized'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_brand_mentions_type')
        batch_op.drop_index(batch_op.f('ix_brand_mentions_message_id'))
        batch_op.drop_index(batch_op.f('ix_brand_mentions_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_brand_mentions_brand_normalized'))
        batch_op.drop_index(batch_op.f('ix_brand_mentions_brand_name'))
        batch_op.drop_index('ix_brand_mentions_brand_date')

    op.drop_table('brand_mentions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_seq')
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('visibility_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visibility_scores_date'))
        batch_op.drop_index(batch_op.f('ix_visibility_scores_brand_normalized'))
        batch_op.drop_index(batch_op.f('ix_visibility_scores_brand_name'))
        batch_op.drop_index('ix_visibility_date_score')
        batch_op.drop_index('ix_visibility_brand_date')

    op.drop_table('visibility_scores')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.drop_index('ix_conversations_session')
        batch_op.drop_index('ix_conversations_platform_date')
        batch_op.drop_index(batch_op.f('ix_conversations_platform'))

    op.drop_table('conversations')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
