"""add_citation_models

Revision ID: 86e370b23d24
Revises: 2453460ad919
Create Date: 2026-01-13 19:45:36.831157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e370b23d24'
down_revision: Union[str, None] = '2453460ad919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('normalized_domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('first_cited_at', sa.DateTime(), nullable=False),
    sa.Column('last_cited_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Manually verified source'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citation_sources', schema=None) as batch_op:
        batch_op.create_index('ix_citation_sources_authority', ['authority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_sources_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_citation_sources_normalized_domain'), ['normalized_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_citation_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index('ix_citation_sources_type_count', ['source_type', 'citation_count'], unique=False)

    op.create_table('website_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False, comment='Pages analyzed'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False, comment='0-100 percent'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('citation_contexts_json', sa.JSON(), nullable=True),
    sa.Column('recommendations_json', sa.JSON(), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False, comment='Total chars analyzed'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Cache expiration'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_website_analyses_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_analyses_domain'), ['domain'], unique=False)
        batch_op.create_index('ix_website_analyses_domain_status', ['domain', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_analyses_status'), ['status'], unique=False)

    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('citation_type', sa.String(length=20), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Extraction confidence'),
    sa.Column('context', sa.Text(), nullable=False, comment='Surrounding text context'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Position in response'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_citations_domain_date', ['source_domain', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_source_domain'), ['source_domain'], unique=False)
        batch_op.create_index('ix_citations_type', ['citation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index('ix_citations_type')
        batch_op.drop_index(batch_op.f('ix_citations_source_domain'))
        batch_op.drop_index('ix_citations_domain_date')
        batch_op.drop_index(batch_op.f('ix_citations_created_at'))
        batch_op.drop_index(batch_op.f('ix_citations_conversation_id'))

    op.drop_table('citations')
    with op.batch_alter_table('website_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_analyses_status'))
        batch_op.drop_index('ix_website_analyses_domain_status')
        batch_op.drop_index(batch_op.f('ix_website_analyses_domain'))
        batch_op.drop_index('ix_website_analyses_created')

    op.drop_table('website_analyses')
    with op.batch_alter_table('citation_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_citation_sources_type_count')
        batch_op.drop_index(batch_op.f('ix_citation_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_citation_sources_normalized_domain'))
        batch_op.drop_index(batch_op.f('ix_citation_sources_domain'))
        batch_op.drop_index('ix_citation_sources_authority')

    op.drop_table('citation_sources')
    # ### end Alembic commands ###
